"use client";

import { CheckCircle, ArrowRight, Video, FileText } from "lucide-react";
import { motion } from "framer-motion";

export default function Features() {
  return (
    <section className="py-24 px-6 md:px-12 max-w-7xl mx-auto flex flex-col gap-6">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Card 1 */}
        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8 }}
          className="bg-[#F6F8FA] rounded-[32px] p-10 flex flex-col items-start gap-4"
        >
          <h2 className="text-3xl md:text-4xl font-semibold text-[#1C1D20] leading-tight max-w-sm">
            Who are you really talking to?
          </h2>
          <p className="text-[#6B6D76] text-lg max-w-sm font-medium mb-8">
            Learn everything about anyone before every call — where they work, what they do, and more.
          </p>
          <div className="w-full bg-white rounded-2xl shadow-sm border border-gray-100 p-6 flex flex-col gap-4 mt-auto">
            <div className="flex items-center justify-between">
              <div className="h-6 w-32 bg-gray-100 rounded-full"></div>
            </div>
            <div className="flex items-center gap-3 mt-2 border-b border-gray-50 pb-4">
              <div className="h-10 w-10 bg-gray-200 rounded-full"></div>
              <div>
                <div className="font-semibold text-gray-800">Roy Lee</div>
                <div className="text-sm text-gray-500">San Francisco • CEO</div>
              </div>
            </div>
            <p className="text-sm text-gray-600 mt-2">
              21-year-old CEO of Cluely, an AI real-time meeting assistant.
            </p>
          </div>
        </motion.div>

        {/* Card 2 */}
        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="bg-[#F6F8FA] rounded-[32px] p-10 flex flex-col items-start gap-4 overflow-hidden relative"
        >
          <div className="w-full bg-white rounded-t-2xl shadow-[0_0_40px_rgba(0,0,0,0.05)] border border-gray-100 p-6 -mt-4 mb-4 flex flex-col gap-4">
            <div className="flex items-center justify-between border-b border-gray-50 pb-3">
               <div className="flex items-center gap-2">
                 <div className="w-6 h-6 bg-gray-200 rounded-full" />
                 <span className="text-sm font-medium">Roy Lee</span>
               </div>
               <div className="w-8 h-4 bg-gray-100 rounded-full" />
            </div>
            <div className="flex flex-col gap-2 opacity-50">
               <div className="w-full h-2 bg-gray-100 rounded-full" />
               <div className="w-3/4 h-2 bg-gray-100 rounded-full" />
            </div>
            <div className="mt-4">
              <h4 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Meeting Notes</h4>
              <h3 className="font-semibold text-lg text-gray-800">Opening and Introductions</h3>
              <div className="w-full h-2 bg-gray-100 rounded-full mt-3" />
              <div className="w-5/6 h-2 bg-gray-100 rounded-full mt-2" />
            </div>
          </div>
          
          <h2 className="text-3xl md:text-4xl font-semibold text-[#1C1D20] leading-tight">
            Beautiful meeting notes
          </h2>
          <p className="text-[#6B6D76] text-lg font-medium">
            Instant shareable meeting notes generated by AI.
          </p>
        </motion.div>
      </div>
    </section>
  );
}

